### ISSUE TITLE
Regarding distribution

### ISSUE THREAD

**Issue by dreamscached** [SolicenTEAM/MAS_RPC#1]
Text in Russian follows.

Greetings. I'm glad you made up your mind and decided to remove an indeed provocative statement in the end of the README, but there's still one thing I want you to know.

You aren't completely correct about the fact you're allowed to rule over the submod, at least outside the Russian-speaking community. Over its short life this submod was maintained by 2 or even 3 maintainers, and ImKventis is the first of them and still has the power over the mod. This mod was not deleted intentionally by its author, it was transferred to Otter and later on (following her leaving the MAS community) was de-facto left for me and other people who were close to Otter and ImKventis (I'm her (most likely, now ex-) close friend and co-developer of her other mods).

Unfortunately, due to Otter leaving and deleting all the repositories (I'll say it right here, this statement applies to all of the other mods that she has released, as I have immediately partook in the development along with other people), the mod you reuploaded has also been deleted, after it was transferred to her account by ImKventis.

However the fact that you have picked up and resurrected the mod doesn't grant you a permission to have full control over it under its name as if it was your own, or copy its code and release it under your name, at least because the author of it is alive, is in good health and clear mind and still has all the rights over his creation and deserves basic respect and not getting his work stolen.

Thank you for translation the mod and willing to help the community, you're doing a good deed but unfortunately with a fairly concerning intentions regarding the submod's future, which I can figure out looking at commit history and literally the message at the end of the README.

<details>
<summary>Перевод</summary>
Приветствую. Рад, что вы соизволили убрать и впрямь вызывающее примечание внизу ридми, но есть ещё одна вещь, о которой хотелось бы вам сказать.

Вы не вполне правы касательно того, что имеете право распоряжаться судьбой мода, по крайней мере за пределами русскоязычного сообщества. За свою короткую "жизнь" мод был в руках двух, если не сказать трёх мейнтейнеров, и ImKventis из них первый и всё ещё влиятельный. Мод не был удалён намеренно своим автором, он был передан другому человеку, Otter, а позднее (с её уходом из MAS-сообщества) был де-факто оставлен мне и другим людям, которые были Otter и ImKventis близки (я являюсь её (скорее всего, бывшим) близким другом и соучастником разработки других модов).

К сожалению, как я сказал выше, из-за ухода Otter и удаления всех репозиториев (сразу скажу, вышесказанное применяется и ко всем остальным модам, которые были ею выпущены, так как я принимал непосредственное участие в их разработке вместе с другими людьми), был удалён и переданный на её аккаунт ImKventis'ом мод, который вы перезалили.

Однако то, что вы его подобрали и "воскресили" не даёт вам права распоряжаться им под этим именем, как своим, или плагиатить, переписывая код и выпуская от своего имени, хотя бы потому, что сам автор жив, находится в добром здравии и ясности рассудка и всё ещё обладает всеми правами на своё творение и заслуживает хотя бы обычного уважения и того, чтобы его работу не крали.

Спасибо за перевод и желание помочь сообществу, вы делаете благое дело, но увы, с несколько настораживающими планами на мод, о чём можно предположить, исходя из истории коммитов и банально сообщения в конце ридми.
</details>

**Comment by DenisSolicen** [comment]
Unfortunately, but all of you (mod developers) have removed its ability to download. You can consider it a fork, or a copy of your mod, which is no longer relevant to you if you so wish. It won't be a problem to rewrite your code, so I don't quite understand the requirements for this mod. 

We planned to continue releasing both the English and Russian versions of the mod, for everyone, but since you don't want it so much, I can only leave the Russian version, which you can consider a fork. We will not use either your Discord API key or other developments in the future, so if you are so outraged by this, then you are only depriving the community of this wonderful mod. 

By the way, I hope you know that @ImKventis contacted me at Discord, and he was not against this mod.

Among other things, I don't understand at all why you so persistently want this submod to disappear forever. I hope we can resolve our dispute peacefully. What is your true claim? 
Did you not indicate in the "Authors" or do not like that someone will work with your brainchild, what exactly is so outraging to you?

**Comment by dreamscached** [comment]
First of, there is no need to escalate it and use strong phrasing. If anything, you were the one instigating such claim by making a provocative statement.

Second of, neither me, nor Kventis

> have removed its ability to download

intentionally.

The submod was transferred to Otter with full trust she will be able to maintain it herself, which she failed at, then has deleted her account not thinking about consequences this would present.

Third of, in the English community I would prefer that you would leave this either to Kventis or me, as we are those people who *directly* have relation to the mod, while you're a mere passerby. I have no claims over Russian version, because as you said, it's a fork.

Once again, what I reached out for is to let you know you cannot make such blatant claims about ownership of stuff you have just found on the net, restored from archives etc. You didn't make it, you did not contribute anyhow in making it, and you cannot say that you reserve a right to take it from here as if nothing happened. Change the name at least and point out it's a fork, only then you have full moral right to do whatever you like as a derivative work.

Edit: I apologize for mentioning getting personal, that's my misunderstanding.

**Comment by DenisSolicen** [comment]
I changed the name of the repository, and added explanations that this is a fork. I hope everything is fine now.
I'm sorry if I was rude to you, have a nice day.

**Comment by dreamscached** [comment]
Thank you. You're doing great job helping the community, I'm sure Russian-speaking players will really appreciate your work!
